project_id = "auzbmfwdxprtvjsvcxcj"

[functions.create-payment-session]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false

[functions.paystack-webhook]
verify_jwt = false

[functions.claim-my-enrolments]
verify_jwt = true

[functions.delete-account]
verify_jwt = true

[functions.verify-admin-access-code]
verify_jwt = true

[functions.create-tutor-account]
verify_jwt = true

[functions.create-live-class-token]
verify_jwt = true

[functions.admin-list-people]
verify_jwt = true

[functions.end-live-class]
verify_jwt = true
